// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBStm-y5lvmlV9bQOpzkl6cjqzBLmBRP-A',
    appId: '1:478523704329:web:6aada052ee69b2dd9c64d8',
    messagingSenderId: '478523704329',
    projectId: 'primefit-82ca9',
    authDomain: 'primefit-82ca9.firebaseapp.com',
    storageBucket: 'primefit-82ca9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADTWOApH1l2FBCmIF4wSsqjhhpGRvoC1c',
    appId: '1:478523704329:android:a20f8a8ca1583e129c64d8',
    messagingSenderId: '478523704329',
    projectId: 'primefit-82ca9',
    storageBucket: 'primefit-82ca9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS7kWCOi4OeMo9mIVhe_79dlK7RAH50mQ',
    appId: '1:478523704329:ios:403ba4c7d14c691d9c64d8',
    messagingSenderId: '478523704329',
    projectId: 'primefit-82ca9',
    storageBucket: 'primefit-82ca9.firebasestorage.app',
    iosBundleId: 'com.example.primefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS7kWCOi4OeMo9mIVhe_79dlK7RAH50mQ',
    appId: '1:478523704329:ios:403ba4c7d14c691d9c64d8',
    messagingSenderId: '478523704329',
    projectId: 'primefit-82ca9',
    storageBucket: 'primefit-82ca9.firebasestorage.app',
    iosBundleId: 'com.example.primefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBStm-y5lvmlV9bQOpzkl6cjqzBLmBRP-A',
    appId: '1:478523704329:web:931b5e508c10b22d9c64d8',
    messagingSenderId: '478523704329',
    projectId: 'primefit-82ca9',
    authDomain: 'primefit-82ca9.firebaseapp.com',
    storageBucket: 'primefit-82ca9.firebasestorage.app',
  );
}
